#!/usr/bin/env python
#
# An example hook script to prepare a packed repository for use over
# dumb transports.
#
# To enable this hook, rename this file to "post-update".

from subprocess import check_output
import os

def run_command(cmd:str, cwd:str) -> str:
    """
    This method will run the commnad and return the result
    """
    output = check_output(cmd.split(),cwd=cwd).decode('utf-8').rsplit('\n')
    return output

def trim_commit(commit:str) -> str:
    """
    This command trims the commit output to 8 character
    """
    return commit[:8]

def get_last_commit_id() -> str:
    """
    This method returns the last commit id from the GIT_SRC_FOLDER
    """
    working_dir = os.getcwd()
    os.chdir(working_dir)
    print(working_dir)
    cmd = 'git log -1 --pretty=format:"%H" '
    output = run_command(cmd, working_dir)[0]
    output = output.replace('"','')
    return output

commit_id = get_last_commit_id()
git_cmd = 'git config remote.origin.url'
output=run_command(git_cmd, cwd=os.getcwd())[0]
print(output.replace(".git", f"/commit/{commit_id}"))

